### ISSUE TITLE
小组管理页面布局异常

### ISSUE THREAD

**Issue by kastnerorz** [shuoj/shu-online-judge-fe#17]
<img width="1429" alt="Screen Shot 2019-11-03 at 1 10 49 AM" src="https://user-images.githubusercontent.com/26199342/68074533-fc588880-fdd6-11e9-9e19-4ee974588552.png">

**Comment by zhangyuiris** [comment]
拉下最新代码

**Comment by kastnerorz** [comment]
safari依然异常
