### ISSUE TITLE
General Test (03-06)

### ISSUE THREAD

**Issue by kastnerorz** [shuoj/shu-online-judge-fe#2]
## 题目页面
1. 通过率显示异常
![image](https://user-images.githubusercontent.com/26199342/53822267-61d74980-3faa-11e9-8265-877292e01393.png)

## 排名页面
1. 我的数据显示异常
![screen shot 2019-03-06 at 12 25 52 am](https://user-images.githubusercontent.com/26199342/53821008-e5dc0200-3fa7-11e9-8341-f981d1812c2b.png)

2. AC率显示异常
![screen shot 2019-03-06 at 12 26 36 am](https://user-images.githubusercontent.com/26199342/53821088-0b690b80-3fa8-11e9-897d-c080eca97311.png)

## 题目列表管理页面
1. 编辑跳转时获取 problem 信息URL错误导致获取失败

## 代码分享页面
1. 显示效果欠佳
![image](https://user-images.githubusercontent.com/26199342/53823086-03ab6600-3fac-11e9-921b-379160f76488.png)

## 比赛列表页面
1. 普通用户在点进私有赛时，无权限无提示，只是空白的骨架
![image](https://user-images.githubusercontent.com/26199342/53823371-9cda7c80-3fac-11e9-8cff-64ffa6998727.png)
建议弹窗告知没权限
1. 普通用户不能加入带密码的比赛

## 小组列表管理页面
1. 小组 id 显示异常
![image](https://user-images.githubusercontent.com/26199342/53822484-cb575800-3faa-11e9-9c9d-d58b53afdb71.png)

## 小组信息管理页面
1. 成员 id 显示异常
![image](https://user-images.githubusercontent.com/26199342/53822801-6819f580-3fab-11e9-96e3-3f3b8d01bd42.png)

2. 在小组有多个成员时，删除某个成员会使所有成员显示消失，而且实际上删除成功却显示删除失败

> 注： 删除接口返回的是小组剩余成员列表，可以直接替换渲染数据

**Comment by zhangyuiris** [comment]
改好了
