### ISSUE TITLE
bug 除了上次的

### ISSUE THREAD

**Issue by bossxu** [shuoj/shu-online-judge-fe#3]
无法创建题目，
+ 上传文件出错
![image](https://user-images.githubusercontent.com/31196107/57229919-bdc15b80-7049-11e9-9818-852cc896e60e.png)
+ 题目上传出错 (post url?)
![image](https://user-images.githubusercontent.com/31196107/57229988-ecd7cd00-7049-11e9-9c86-d48752abc09c.png)
+

**Comment by zhangyuiris** [comment]
要按照格式upload zip文件
